# Generated by Django 4.2.23 on 2025-09-15 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__name": "owner"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="restaurant_description",
            field=models.TextField(
                blank=True, help_text="Description of the restaurant (for owners only)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="restaurant_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the restaurant (for owners only)",
                max_length=200,
            ),
        ),
    ]
