# Generated by Django 4.2.23 on 2025-09-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_owner_user_restaurant_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("administrator", "Administrator"),
                    ("owner", "Owner"),
                    ("customer_care", "Customer Care"),
                    ("kitchen", "Kitchen"),
                    ("cashier", "Cashier"),
                    ("customer", "Customer"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
