# Generated by Django 4.2.7 on 2025-09-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_role_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="restaurant_qr_code",
            field=models.CharField(
                blank=True,
                help_text="Unique QR code for restaurant access",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
    ]
