# Generated by Django 4.2.7 on 2025-10-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_restaurant_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('owner', 'Owner'), ('customer_care', 'Customer Care'), ('kitchen', 'Kitchen'), ('bar', 'Bar'), ('cashier', 'Cashier'), ('customer', 'Customer')], max_length=20, unique=True),
        ),
    ]
