# Generated by Django 4.2.7 on 2025-10-14 07:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0800'), help_text='Tax rate as decimal (e.g., 0.0800 for 8%, 0.0500 for 5%)', max_digits=5),
        ),
    ]
