# Generated by Django 4.2.7 on 2025-09-29 11:20

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0005_alter_happyhourpromotion_discount_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('overall', 'Overall'), ('category', 'By Category'), ('subcategory', 'By Sub Category')], max_length=20)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom Range')], max_length=20)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_items_sold', models.IntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cash_payments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('card_payments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('digital_payments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('voucher_payments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_discounts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.maincategory')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_reports', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.subcategory')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSalesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('average_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.product')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='reports.salesreport')),
            ],
            options={
                'ordering': ['-quantity_sold', '-total_revenue'],
            },
        ),
        migrations.CreateModel(
            name='HourlyBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('orders_count', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_breakdown', to='reports.salesreport')),
            ],
            options={
                'ordering': ['hour'],
            },
        ),
        migrations.CreateModel(
            name='CashierPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_processed', models.IntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cash_handled', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('void_transactions', models.IntegerField(default=0)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_performance', to='reports.salesreport')),
            ],
            options={
                'ordering': ['-total_sales', '-orders_processed'],
            },
        ),
        migrations.AddIndex(
            model_name='salesreport',
            index=models.Index(fields=['owner', 'date_from', 'date_to'], name='reports_sal_owner_i_aa60d0_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreport',
            index=models.Index(fields=['report_type', 'period_type'], name='reports_sal_report__f55957_idx'),
        ),
        migrations.AddIndex(
            model_name='productsalesdetail',
            index=models.Index(fields=['report', 'quantity_sold'], name='reports_pro_report__0bd85a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hourlybreakdown',
            unique_together={('report', 'hour')},
        ),
    ]
