# Generated by Django 4.2.23 on 2025-09-15 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maincategory",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__name": "owner"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tableinfo",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role__name": "owner"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="maincategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tableinfo",
            name="tbl_no",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name="maincategory",
            unique_together={("owner", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="tableinfo",
            unique_together={("owner", "tbl_no")},
        ),
    ]
