# Generated by Django 4.2.7 on 2025-09-29 07:17

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0003_alter_product_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyHourPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Happy Hour Special', 'Weekend Discount'", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of the promotion')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (1-99)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MinValueValidator(Decimal('99.99'))])),
                ('start_time', models.TimeField(help_text='Start time for the promotion')),
                ('end_time', models.TimeField(help_text='End time for the promotion')),
                ('days_of_week', models.CharField(help_text="Comma-separated days (1=Mon, 7=Sun), e.g., '1,2,3,4,5' for weekdays", max_length=13)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this promotion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_categories', models.ManyToManyField(blank=True, help_text='Main categories for this promotion', related_name='happy_hour_promotions', to='restaurant.maincategory')),
                ('owner', models.ForeignKey(limit_choices_to={'role__name': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='happy_hour_promotions', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, help_text='Specific products for this promotion', related_name='happy_hour_promotions', to='restaurant.product')),
                ('sub_categories', models.ManyToManyField(blank=True, help_text='Sub categories for this promotion', related_name='happy_hour_promotions', to='restaurant.subcategory')),
            ],
            options={
                'verbose_name': 'Happy Hour Promotion',
                'verbose_name_plural': 'Happy Hour Promotions',
                'ordering': ['-created_at'],
            },
        ),
    ]
