# Generated by Django 4.2.7 on 2025-09-29 07:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_happyhourpromotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happyhourpromotion',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, help_text='Discount percentage (1-99)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('99.99'))]),
        ),
    ]
