# Generated by Django 4.2.7 on 2025-10-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_product_image_maincategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='station',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('bar', 'Bar')], default='kitchen', help_text='Assign to kitchen or bar', max_length=20),
        ),
    ]
