# Generated by Django 4.2.23 on 2025-09-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("preparing", "Preparing"),
                    ("ready", "Ready"),
                    ("served", "Served"),
                    ("cancelled", "Cancelled"),
                    ("customer_refused", "Customer Refused"),
                    ("kitchen_error", "Kitchen Error"),
                    ("quality_issue", "Quality Issue"),
                    ("wasted", "Food Wasted"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
